os:
  - linux
  - osx

#compiler:
#  - gcc
#  - clang

# sudo: required
# dist: trusty
language: cpp
# compiler:
#   - gcc

#addons:
#  apt:
#    packages:
#      - libsfml-dev


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler:
        - gcc
    - os: osx
      osx_image: xcode7.2
      compiler:
        - clang
# before_script:
#   - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 cppcheck libsfml-dev

#script:
#  lsb_relea<F12>se -a
#  cmake .
#  make
#qmake -makefile pagan_board.pro && make && make && cppcheck . --enable=all 

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/travis_before_install_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh scripts/travis_before_install_osx.sh; fi
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - ps axu |grep Xvfb -i
  - sleep 4  


before_script:
  - "export DISPLAY=:99.0"
  - glxinfo
  - sleep 4 # give xvfb some time to start
  - echo "GOOO"


script:
  - bash scripts/travis_make.sh
    #  - "export DISPLAY=:99.0"
    #  - cmake .
    #  - ps axu |grep Xvfb -i
    #  - glxinfo    
    #  - ./DeerPortal-0.8.1-x86_64.AppImage
    #  - DISPLAY=:1 xwd -root -silent | convert xwd:- png:screenshot.png
